#
# https://github.com/P3TERX/Actions-OpenWrt
#
# File: .github/workflows/openwrt-bulder.yml
# Description: Build OpenWrt using GitHub Actions
#
# Copyright (c) 2019-2024 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: Lede tagSL OpenWrt Builder

on:
  repository_dispatch:
  workflow_dispatch:
     inputs:
          tagSL:
            description: "请选择lede版本:"
            required: true
            default: 'master'
            type: choice
            options:
              - 'master'
              - '20230609'
              - '20221001'
              - '20220716'
              - '20220505'
              - '20220401'
              - '20211117'
              - '20200915'
              - '20200416'
              - '20200408'
              

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: ${{ github.event.client_payload.tagSL || github.event.inputs.tagSL }}
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: lede-jingjian.config
  DIY_P1_SH: diy-ledeSL-part1.sh
  DIY_P2_SH: diy-part2.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
   run-ubuntu:
    runs-on: ubuntu-22.04
    if: tagSL == 'master' || tagSL == '20230609' || tagSL == '20221001' || tagSL == '20220716' || tagSL == '20220505' || tagSL == '20220401' 
    steps:
     - name: Run Ubuntu Task
       run: echo "你选择的版本是: ${{tagSL}},配合这个版本的编译系统版本是ubuntu-22.04"
   
   run-ubuntu1:
    runs-on: ubuntu-20.04
    if: tagSL == '20211117' || tagSL == '20200915' || tagSL == '20200416' || tagSL == '20200408' 
    steps:
     - name: Run Ubuntu1 Task
       run: echo "你选择的版本是: ${{tagSL}},配合这个版本的编译系统版本是ubuntu-20.04"
  
   

    
